/**
 * Cross-validates the JS interior-point cvxEDA solver against real ground
 * truth from the actual upstream `cvxEDA.py` (lciti/cvxEDA) -- not just
 * self-consistency checks against the JS's own prior output.
 *
 * The fixture (fixtures/cvxeda_reference.json) was generated by
 * tests/manual/gen_cvxeda_reference.py, which fetches and runs the live
 * reference implementation against real `cvxopt`. Regenerate it with that
 * script (needs `pip install numpy cvxopt` + network access) if the
 * reference algorithm changes or a different synthetic case is wanted --
 * this test file itself needs neither Python nor network access to run.
 *
 * Run: node --test tests/test_cvxeda_reference.js
 */

'use strict';

const assert = require('assert');
const test = require('node:test');
const path = require('path');
const vm = require('vm');
const fs = require('fs');

global.window = global;
global.GSR_CONST = require('./mock_constants.js');

function loadModule(filePath, varName) {
  const src = fs.readFileSync(filePath, 'utf8');
  const wrapped = src.replace(new RegExp('const ' + varName + '\\s*='), 'global.' + varName + ' =');
  vm.runInThisContext(wrapped, { filename: filePath });
}
loadModule(path.join(__dirname, '../src/signal/cvxeda.js'), 'CVXEDA');
const { CVXEDA } = global;

const ref = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures/cvxeda_reference.json'), 'utf8'));

function relRMSE(a, b) {
  let num = 0, den = 0;
  for (let i = 0; i < a.length; i++) { const d = a[i] - b[i]; num += d * d; den += b[i] * b[i]; }
  return Math.sqrt(num / Math.max(den, 1e-30));
}

test('cvxEDA vs real cvxopt reference: phasic/tonic/driver/l/d/obj all match to well within 1e-2 relative', () => {
  // ref.y_z is already zscored (population std, matching normalize:true's
  // convention) -- feed with normalize:false for an apples-to-apples
  // comparison in the same space the reference itself solved in. Also pin
  // alpha/gamma/tau/knot spacing to what gen_cvxeda_reference.py actually
  // used (the reference paper's defaults) rather than letting them fall
  // through to GSR_CONST.CVXEDA's app-tuned alpha (2e-3, not 8e-4) --
  // otherwise this compares two different problems, not two solvers on the
  // same one.
  const res = CVXEDA.decompose(Float64Array.from(ref.y_z), ref.sr, {
    normalize: false, alpha: 8e-4, gamma: 1e-2, tauSlow: 2.0, tauFast: 0.7, deltaKnotSec: 10.0
  });
  assert.ok(res.converged, 'reference cross-check signal should converge');
  assert.strictEqual(res.pivotFires, 0, 'a clean, well-conditioned reference solve should never need the pivot floor');

  const phasicErr = relRMSE(res.phasic, ref.r);
  const tonicErr = relRMSE(res.tonic, ref.t);
  const driverErr = relRMSE(res.driver, ref.p);
  const lErr = relRMSE(res.l, ref.l);

  // Thresholds are set an order of magnitude (or more) above what's actually
  // observed (~1e-5 to 1e-7) -- tight enough to catch a real regression in
  // the solver, loose enough not to flake on a legitimate future tuning pass.
  assert.ok(phasicErr < 1e-3, `phasic relRMSE vs real cvxopt should be < 1e-3, got ${phasicErr.toExponential(2)}`);
  assert.ok(tonicErr < 1e-3, `tonic relRMSE vs real cvxopt should be < 1e-3, got ${tonicErr.toExponential(2)}`);
  assert.ok(driverErr < 1e-2, `driver relRMSE vs real cvxopt should be < 1e-2, got ${driverErr.toExponential(2)}`);
  assert.ok(lErr < 1e-3, `spline coeff relRMSE vs real cvxopt should be < 1e-3, got ${lErr.toExponential(2)}`);

  assert.ok(Math.abs(res.d[0] - ref.d[0]) < 1e-2, `drift offset ${res.d[0]} should match reference ${ref.d[0]}`);
  assert.ok(Math.abs(res.d[1] - ref.d[1]) < 1e-2, `drift slope ${res.d[1]} should match reference ${ref.d[1]}`);
  const objErr = Math.abs(res.obj - ref.obj) / Math.abs(ref.obj);
  assert.ok(objErr < 1e-3, `objective value should match reference within 1e-3 relative, got ${objErr.toExponential(2)}`);
});
